# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in dlp_admin.gemspec.
gemspec

gem "puma"

gem "pg"

# Start debugger with binding.b [https://github.com/ruby/debug]
# gem "debug", ">= 1.0.0"
